name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ ì´ jobì€ ${{ github.event_name }} eventì— ì˜í•´ triggerë©ë‹ˆë‹¤."
      - run: echo "ğŸ§ ì´ jobì€ GitHubì˜ ${{ runner.os }} serverì—ì„œ hostë©ë‹ˆë‹¤."
      - run: echo "ğŸ” branchì˜ ì´ë¦„ì€ ${{ github.ref }}ì´ê³ , ì €ì¥ì†Œ(repository)ì˜ ì´ë¦„ì€ ${{ github.repository }}ì…ë‹ˆë‹¤."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ ${{ github.repository }} ì €ì¥ì†Œê°€ runner(ì‹¤í–‰ ì¤‘ì¸ GitHub Actions ê°€ìƒ í™˜ê²½)ë¡œ ë³µì œ(clone)ë˜ì—ˆìŠµë‹ˆë‹¤."
      - run: echo "ğŸ–¥ï¸ ì›Œí¬í”Œë¡œê°€ runner ìƒì—ì„œ ë‹¹ì‹ ì˜ ì½”ë“œë¥¼ í…ŒìŠ¤íŠ¸í•  ì¤€ë¹„ê°€ ë˜ì—ˆìŠµë‹ˆë‹¤."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ jobì˜ ìƒíƒœ(status): ${{ job.status }}."
